name: Contract Testing Pipeline

on:
  push:
    branches:
      - master
      - all-tests

  pull_request:

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'
      - name: Install Git
        run: sudo apt install git -y
      - name: Install node modules
        run: yarn
      # - name: Give the right to launch the sandbox
      #   run: chmod 777 ./ci/flextesa.sh
      # - name: Run ganache-cli in background
      #   run: ./ci/flextesa.sh
      - name: Compile and test contracts
        run: yarn compile && yarn test
