name: Contract Testing Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Git
        run: sudo apt install git -y
      - name: Install node modules
        run: yarn
      - name: Give the right to launch the sandbox
        run: chmod 777 ./ci/flextesa.sh
      - name: Run ganache-cli in background
        run: ./ci/flextesa.sh
      - name: Compile and test contracts
        run: yarn compile && yarn test
